# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raging_tools.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 853)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 931, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.vram_explorer = QtWidgets.QWidget()
        self.vram_explorer.setObjectName("vram_explorer")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.vram_explorer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 70, 821, 651))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.imageTexture = QtWidgets.QLabel(self.frame)
        self.imageTexture.setGeometry(QtCore.QRect(40, 60, 461, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageTexture.sizePolicy().hasHeightForWidth())
        self.imageTexture.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.imageTexture.setPalette(palette)
        self.imageTexture.setAutoFillBackground(False)
        self.imageTexture.setText("")
        self.imageTexture.setScaledContents(False)
        self.imageTexture.setAlignment(QtCore.Qt.AlignCenter)
        self.imageTexture.setObjectName("imageTexture")
        self.exportButton = QtWidgets.QPushButton(self.frame)
        self.exportButton.setGeometry(QtCore.QRect(370, 580, 75, 23))
        self.exportButton.setObjectName("exportButton")
        self.importButton = QtWidgets.QPushButton(self.frame)
        self.importButton.setGeometry(QtCore.QRect(450, 580, 75, 23))
        self.importButton.setObjectName("importButton")
        self.sizeImageText = QtWidgets.QLabel(self.frame)
        self.sizeImageText.setGeometry(QtCore.QRect(20, 10, 150, 16))
        self.sizeImageText.setText("")
        self.sizeImageText.setAlignment(QtCore.Qt.AlignCenter)
        self.sizeImageText.setObjectName("sizeImageText")
        self.encodingImageText = QtWidgets.QLabel(self.frame)
        self.encodingImageText.setGeometry(QtCore.QRect(379, 10, 150, 16))
        self.encodingImageText.setText("")
        self.encodingImageText.setAlignment(QtCore.Qt.AlignCenter)
        self.encodingImageText.setObjectName("encodingImageText")
        self.mipMapsImageText = QtWidgets.QLabel(self.frame)
        self.mipMapsImageText.setGeometry(QtCore.QRect(200, 10, 150, 16))
        self.mipMapsImageText.setText("")
        self.mipMapsImageText.setAlignment(QtCore.Qt.AlignCenter)
        self.mipMapsImageText.setObjectName("mipMapsImageText")
        self.horizontalLayout.addWidget(self.frame)
        self.exportAllButton = QtWidgets.QPushButton(self.vram_explorer)
        self.exportAllButton.setGeometry(QtCore.QRect(130, 40, 75, 23))
        self.exportAllButton.setObjectName("exportAllButton")
        self.fileNameText = QtWidgets.QLabel(self.vram_explorer)
        self.fileNameText.setGeometry(QtCore.QRect(40, 20, 841, 20))
        self.fileNameText.setText("")
        self.fileNameText.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNameText.setObjectName("fileNameText")
        self.tabWidget.addTab(self.vram_explorer, "")
        self.character_parameters_editor = QtWidgets.QWidget()
        self.character_parameters_editor.setObjectName("character_parameters_editor")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.character_parameters_editor)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 871, 701))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.portrait = QtWidgets.QLabel(self.frame_2)
        self.portrait.setGeometry(QtCore.QRect(0, 300, 271, 271))
        self.portrait.setText("")
        self.portrait.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/large/chara_up_chips_l_000.png"))
        self.portrait.setScaledContents(True)
        self.portrait.setObjectName("portrait")
        self.mainPanel = QtWidgets.QFrame(self.frame_2)
        self.mainPanel.setGeometry(QtCore.QRect(0, 500, 681, 201))
        self.mainPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPanel.setObjectName("mainPanel")
        self.label_67 = QtWidgets.QLabel(self.mainPanel)
        self.label_67.setGeometry(QtCore.QRect(40, 40, 41, 41))
        self.label_67.setText("")
        self.label_67.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_67.setScaledContents(True)
        self.label_67.setWordWrap(False)
        self.label_67.setObjectName("label_67")
        self.label_72 = QtWidgets.QLabel(self.mainPanel)
        self.label_72.setGeometry(QtCore.QRect(40, 80, 41, 41))
        self.label_72.setText("")
        self.label_72.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_72.setScaledContents(True)
        self.label_72.setObjectName("label_72")
        self.label_71 = QtWidgets.QLabel(self.mainPanel)
        self.label_71.setGeometry(QtCore.QRect(40, 120, 41, 41))
        self.label_71.setText("")
        self.label_71.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_71.setScaledContents(True)
        self.label_71.setObjectName("label_71")
        self.label_78 = QtWidgets.QLabel(self.mainPanel)
        self.label_78.setGeometry(QtCore.QRect(40, 160, 41, 41))
        self.label_78.setText("")
        self.label_78.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_78.setScaledContents(True)
        self.label_78.setObjectName("label_78")
        self.label_93 = QtWidgets.QLabel(self.mainPanel)
        self.label_93.setGeometry(QtCore.QRect(0, 120, 41, 41))
        self.label_93.setText("")
        self.label_93.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_93.setScaledContents(True)
        self.label_93.setObjectName("label_93")
        self.label_77 = QtWidgets.QLabel(self.mainPanel)
        self.label_77.setGeometry(QtCore.QRect(80, 40, 41, 41))
        self.label_77.setText("")
        self.label_77.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_77.setScaledContents(True)
        self.label_77.setObjectName("label_77")
        self.label_66 = QtWidgets.QLabel(self.mainPanel)
        self.label_66.setGeometry(QtCore.QRect(80, 160, 41, 41))
        self.label_66.setText("")
        self.label_66.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName("label_66")
        self.label_63 = QtWidgets.QLabel(self.mainPanel)
        self.label_63.setGeometry(QtCore.QRect(80, 120, 41, 41))
        self.label_63.setText("")
        self.label_63.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_63.setScaledContents(True)
        self.label_63.setObjectName("label_63")
        self.label_62 = QtWidgets.QLabel(self.mainPanel)
        self.label_62.setGeometry(QtCore.QRect(80, 80, 41, 41))
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.label_85 = QtWidgets.QLabel(self.mainPanel)
        self.label_85.setGeometry(QtCore.QRect(120, 40, 41, 41))
        self.label_85.setText("")
        self.label_85.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_85.setScaledContents(True)
        self.label_85.setObjectName("label_85")
        self.label_76 = QtWidgets.QLabel(self.mainPanel)
        self.label_76.setGeometry(QtCore.QRect(120, 160, 41, 41))
        self.label_76.setText("")
        self.label_76.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_76.setScaledContents(True)
        self.label_76.setObjectName("label_76")
        self.label_58 = QtWidgets.QLabel(self.mainPanel)
        self.label_58.setGeometry(QtCore.QRect(120, 120, 41, 41))
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.label_84 = QtWidgets.QLabel(self.mainPanel)
        self.label_84.setGeometry(QtCore.QRect(120, 80, 41, 41))
        self.label_84.setText("")
        self.label_84.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_84.setScaledContents(True)
        self.label_84.setObjectName("label_84")
        self.label_16 = QtWidgets.QLabel(self.mainPanel)
        self.label_16.setGeometry(QtCore.QRect(160, 40, 41, 41))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_74 = QtWidgets.QLabel(self.mainPanel)
        self.label_74.setGeometry(QtCore.QRect(160, 160, 41, 41))
        self.label_74.setText("")
        self.label_74.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_74.setScaledContents(True)
        self.label_74.setObjectName("label_74")
        self.label_39 = QtWidgets.QLabel(self.mainPanel)
        self.label_39.setGeometry(QtCore.QRect(160, 120, 41, 41))
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_38 = QtWidgets.QLabel(self.mainPanel)
        self.label_38.setGeometry(QtCore.QRect(160, 80, 41, 41))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_70 = QtWidgets.QLabel(self.mainPanel)
        self.label_70.setGeometry(QtCore.QRect(200, 40, 41, 41))
        self.label_70.setText("")
        self.label_70.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_70.setScaledContents(True)
        self.label_70.setObjectName("label_70")
        self.label_21 = QtWidgets.QLabel(self.mainPanel)
        self.label_21.setGeometry(QtCore.QRect(200, 160, 41, 41))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_90 = QtWidgets.QLabel(self.mainPanel)
        self.label_90.setGeometry(QtCore.QRect(200, 120, 41, 41))
        self.label_90.setText("")
        self.label_90.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_90.setScaledContents(True)
        self.label_90.setObjectName("label_90")
        self.label_92 = QtWidgets.QLabel(self.mainPanel)
        self.label_92.setGeometry(QtCore.QRect(200, 80, 41, 41))
        self.label_92.setText("")
        self.label_92.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_92.setScaledContents(True)
        self.label_92.setObjectName("label_92")
        self.label_29 = QtWidgets.QLabel(self.mainPanel)
        self.label_29.setGeometry(QtCore.QRect(240, 40, 41, 41))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_36 = QtWidgets.QLabel(self.mainPanel)
        self.label_36.setGeometry(QtCore.QRect(240, 160, 41, 41))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_31 = QtWidgets.QLabel(self.mainPanel)
        self.label_31.setGeometry(QtCore.QRect(240, 120, 41, 41))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_27 = QtWidgets.QLabel(self.mainPanel)
        self.label_27.setGeometry(QtCore.QRect(240, 80, 41, 41))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_04 = QtWidgets.QLabel(self.mainPanel)
        self.label_04.setGeometry(QtCore.QRect(280, 40, 41, 41))
        self.label_04.setText("")
        self.label_04.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_04.setScaledContents(True)
        self.label_04.setObjectName("label_04")
        self.label_73 = QtWidgets.QLabel(self.mainPanel)
        self.label_73.setGeometry(QtCore.QRect(280, 160, 41, 41))
        self.label_73.setText("")
        self.label_73.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_73.setScaledContents(True)
        self.label_73.setObjectName("label_73")
        self.label_08 = QtWidgets.QLabel(self.mainPanel)
        self.label_08.setGeometry(QtCore.QRect(280, 120, 41, 41))
        self.label_08.setText("")
        self.label_08.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_08.setScaledContents(True)
        self.label_08.setObjectName("label_08")
        self.label_05 = QtWidgets.QLabel(self.mainPanel)
        self.label_05.setGeometry(QtCore.QRect(280, 80, 41, 41))
        self.label_05.setText("")
        self.label_05.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_05.setScaledContents(True)
        self.label_05.setObjectName("label_05")
        self.label_00 = QtWidgets.QLabel(self.mainPanel)
        self.label_00.setGeometry(QtCore.QRect(320, 40, 41, 41))
        self.label_00.setText("")
        self.label_00.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_00.setScaledContents(True)
        self.label_00.setObjectName("label_00")
        self.label_24 = QtWidgets.QLabel(self.mainPanel)
        self.label_24.setGeometry(QtCore.QRect(320, 160, 41, 41))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_13 = QtWidgets.QLabel(self.mainPanel)
        self.label_13.setGeometry(QtCore.QRect(320, 120, 41, 41))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.mainPanel)
        self.label_12.setGeometry(QtCore.QRect(320, 80, 41, 41))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_17 = QtWidgets.QLabel(self.mainPanel)
        self.label_17.setGeometry(QtCore.QRect(360, 40, 41, 41))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.mainPanel)
        self.label_15.setGeometry(QtCore.QRect(360, 160, 41, 41))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.mainPanel)
        self.label_14.setGeometry(QtCore.QRect(360, 120, 41, 41))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.mainPanel)
        self.label_11.setGeometry(QtCore.QRect(360, 80, 41, 41))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_37 = QtWidgets.QLabel(self.mainPanel)
        self.label_37.setGeometry(QtCore.QRect(400, 40, 41, 41))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_34 = QtWidgets.QLabel(self.mainPanel)
        self.label_34.setGeometry(QtCore.QRect(400, 160, 41, 41))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.label_88 = QtWidgets.QLabel(self.mainPanel)
        self.label_88.setGeometry(QtCore.QRect(400, 120, 41, 41))
        self.label_88.setText("")
        self.label_88.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_88.setScaledContents(True)
        self.label_88.setObjectName("label_88")
        self.label_22 = QtWidgets.QLabel(self.mainPanel)
        self.label_22.setGeometry(QtCore.QRect(400, 80, 41, 41))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_48 = QtWidgets.QLabel(self.mainPanel)
        self.label_48.setGeometry(QtCore.QRect(440, 40, 41, 41))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_81 = QtWidgets.QLabel(self.mainPanel)
        self.label_81.setGeometry(QtCore.QRect(440, 160, 41, 41))
        self.label_81.setText("")
        self.label_81.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_81.setScaledContents(True)
        self.label_81.setObjectName("label_81")
        self.label_79 = QtWidgets.QLabel(self.mainPanel)
        self.label_79.setGeometry(QtCore.QRect(440, 120, 41, 41))
        self.label_79.setText("")
        self.label_79.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_79.setScaledContents(True)
        self.label_79.setObjectName("label_79")
        self.label_82 = QtWidgets.QLabel(self.mainPanel)
        self.label_82.setGeometry(QtCore.QRect(440, 80, 41, 41))
        self.label_82.setText("")
        self.label_82.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_82.setScaledContents(True)
        self.label_82.setObjectName("label_82")
        self.label_43 = QtWidgets.QLabel(self.mainPanel)
        self.label_43.setGeometry(QtCore.QRect(480, 40, 41, 41))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_46 = QtWidgets.QLabel(self.mainPanel)
        self.label_46.setGeometry(QtCore.QRect(480, 160, 41, 41))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.label_45 = QtWidgets.QLabel(self.mainPanel)
        self.label_45.setGeometry(QtCore.QRect(480, 120, 41, 41))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.label_44 = QtWidgets.QLabel(self.mainPanel)
        self.label_44.setGeometry(QtCore.QRect(480, 80, 41, 41))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.label_47 = QtWidgets.QLabel(self.mainPanel)
        self.label_47.setGeometry(QtCore.QRect(520, 40, 41, 41))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.label_98 = QtWidgets.QLabel(self.mainPanel)
        self.label_98.setGeometry(QtCore.QRect(520, 160, 41, 41))
        self.label_98.setText("")
        self.label_98.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_98.setScaledContents(True)
        self.label_98.setObjectName("label_98")
        self.label_97 = QtWidgets.QLabel(self.mainPanel)
        self.label_97.setGeometry(QtCore.QRect(520, 120, 41, 41))
        self.label_97.setText("")
        self.label_97.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_97.setScaledContents(True)
        self.label_97.setObjectName("label_97")
        self.label_96 = QtWidgets.QLabel(self.mainPanel)
        self.label_96.setGeometry(QtCore.QRect(520, 80, 41, 41))
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.label_91 = QtWidgets.QLabel(self.mainPanel)
        self.label_91.setGeometry(QtCore.QRect(560, 40, 41, 41))
        self.label_91.setText("")
        self.label_91.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_91.setScaledContents(True)
        self.label_91.setObjectName("label_91")
        self.label_87 = QtWidgets.QLabel(self.mainPanel)
        self.label_87.setGeometry(QtCore.QRect(560, 160, 41, 41))
        self.label_87.setText("")
        self.label_87.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_87.setScaledContents(True)
        self.label_87.setObjectName("label_87")
        self.label_42 = QtWidgets.QLabel(self.mainPanel)
        self.label_42.setGeometry(QtCore.QRect(560, 120, 41, 41))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.label_40 = QtWidgets.QLabel(self.mainPanel)
        self.label_40.setGeometry(QtCore.QRect(560, 80, 41, 41))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_54 = QtWidgets.QLabel(self.mainPanel)
        self.label_54.setGeometry(QtCore.QRect(600, 40, 41, 41))
        self.label_54.setText("")
        self.label_54.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName("label_54")
        self.label_57 = QtWidgets.QLabel(self.mainPanel)
        self.label_57.setGeometry(QtCore.QRect(600, 160, 41, 41))
        self.label_57.setText("")
        self.label_57.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.label_56 = QtWidgets.QLabel(self.mainPanel)
        self.label_56.setGeometry(QtCore.QRect(600, 120, 41, 41))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_55 = QtWidgets.QLabel(self.mainPanel)
        self.label_55.setGeometry(QtCore.QRect(600, 80, 41, 41))
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.label_99 = QtWidgets.QLabel(self.mainPanel)
        self.label_99.setGeometry(QtCore.QRect(640, 120, 41, 41))
        self.label_99.setText("")
        self.label_99.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_99.setScaledContents(True)
        self.label_99.setObjectName("label_99")
        self.label_trans_0 = QtWidgets.QLabel(self.mainPanel)
        self.label_trans_0.setGeometry(QtCore.QRect(280, 0, 41, 41))
        self.label_trans_0.setText("")
        self.label_trans_0.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_trans_0.setScaledContents(True)
        self.label_trans_0.setObjectName("label_trans_0")
        self.label_trans_1 = QtWidgets.QLabel(self.mainPanel)
        self.label_trans_1.setGeometry(QtCore.QRect(240, 0, 41, 41))
        self.label_trans_1.setText("")
        self.label_trans_1.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_trans_1.setScaledContents(True)
        self.label_trans_1.setObjectName("label_trans_1")
        self.label_trans_2 = QtWidgets.QLabel(self.mainPanel)
        self.label_trans_2.setGeometry(QtCore.QRect(200, 0, 41, 41))
        self.label_trans_2.setText("")
        self.label_trans_2.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_trans_2.setScaledContents(True)
        self.label_trans_2.setObjectName("label_trans_2")
        self.label_trans_3 = QtWidgets.QLabel(self.mainPanel)
        self.label_trans_3.setGeometry(QtCore.QRect(160, 0, 41, 41))
        self.label_trans_3.setText("")
        self.label_trans_3.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/sc_chara_000.bmp"))
        self.label_trans_3.setScaledContents(True)
        self.label_trans_3.setObjectName("label_trans_3")
        self.transformPanel = QtWidgets.QFrame(self.frame_2)
        self.transformPanel.setGeometry(QtCore.QRect(0, 40, 191, 181))
        self.transformPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transformPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transformPanel.setObjectName("transformPanel")
        self.transSlotPanel0 = QtWidgets.QLabel(self.transformPanel)
        self.transSlotPanel0.setEnabled(True)
        self.transSlotPanel0.setGeometry(QtCore.QRect(33, 75, 61, 61))
        self.transSlotPanel0.setText("")
        self.transSlotPanel0.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.transSlotPanel0.setScaledContents(False)
        self.transSlotPanel0.setObjectName("transSlotPanel0")
        self.transSlotPanel1 = QtWidgets.QLabel(self.transformPanel)
        self.transSlotPanel1.setGeometry(QtCore.QRect(65, 43, 61, 61))
        self.transSlotPanel1.setText("")
        self.transSlotPanel1.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.transSlotPanel1.setScaledContents(False)
        self.transSlotPanel1.setObjectName("transSlotPanel1")
        self.transSlotPanel2 = QtWidgets.QLabel(self.transformPanel)
        self.transSlotPanel2.setGeometry(QtCore.QRect(99, 75, 61, 61))
        self.transSlotPanel2.setText("")
        self.transSlotPanel2.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.transSlotPanel2.setScaledContents(False)
        self.transSlotPanel2.setObjectName("transSlotPanel2")
        self.transSlotPanel3 = QtWidgets.QLabel(self.transformPanel)
        self.transSlotPanel3.setGeometry(QtCore.QRect(65, 108, 61, 61))
        self.transSlotPanel3.setText("")
        self.transSlotPanel3.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.transSlotPanel3.setScaledContents(False)
        self.transSlotPanel3.setObjectName("transSlotPanel3")
        self.transText = QtWidgets.QLabel(self.transformPanel)
        self.transText.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.transText.setText("")
        self.transText.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/tx_transform_US.png"))
        self.transText.setScaledContents(True)
        self.transText.setObjectName("transText")
        self.transPanel = QtWidgets.QLabel(self.transformPanel)
        self.transPanel.setGeometry(QtCore.QRect(30, 35, 141, 141))
        self.transPanel.setText("")
        self.transPanel.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/pl_transform.png"))
        self.transPanel.setScaledContents(False)
        self.transPanel.setObjectName("transPanel")
        self.transPanel.raise_()
        self.transText.raise_()
        self.transSlotPanel1.raise_()
        self.transSlotPanel0.raise_()
        self.transSlotPanel2.raise_()
        self.transSlotPanel3.raise_()
        self.transEffect = QtWidgets.QFrame(self.frame_2)
        self.transEffect.setGeometry(QtCore.QRect(190, 0, 261, 41))
        self.transEffect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transEffect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transEffect.setObjectName("transEffect")
        self.transEffectValue = QtWidgets.QComboBox(self.transEffect)
        self.transEffectValue.setGeometry(QtCore.QRect(140, 10, 101, 22))
        self.transEffectValue.setObjectName("transEffectValue")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectValue.addItem("")
        self.transEffectText = QtWidgets.QLabel(self.transEffect)
        self.transEffectText.setGeometry(QtCore.QRect(0, 10, 161, 21))
        self.transEffectText.setObjectName("transEffectText")
        self.transPartner = QtWidgets.QFrame(self.frame_2)
        self.transPartner.setGeometry(QtCore.QRect(190, 40, 261, 51))
        self.transPartner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transPartner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transPartner.setObjectName("transPartner")
        self.transPartnerText = QtWidgets.QLabel(self.transPartner)
        self.transPartnerText.setGeometry(QtCore.QRect(0, 20, 161, 21))
        self.transPartnerText.setObjectName("transPartnerText")
        self.transPartnerValue = QtWidgets.QLabel(self.transPartner)
        self.transPartnerValue.setGeometry(QtCore.QRect(200, 10, 41, 41))
        self.transPartnerValue.setText("")
        self.transPartnerValue.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.transPartnerValue.setScaledContents(True)
        self.transPartnerValue.setObjectName("transPartnerValue")
        self.transPartnerSlot = QtWidgets.QLabel(self.transPartner)
        self.transPartnerSlot.setGeometry(QtCore.QRect(200, 10, 41, 41))
        self.transPartnerSlot.setText("")
        self.transPartnerSlot.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/pl_slot.png"))
        self.transPartnerSlot.setScaledContents(True)
        self.transPartnerSlot.setObjectName("transPartnerSlot")
        self.transPartnerSlot.raise_()
        self.transPartnerText.raise_()
        self.transPartnerValue.raise_()
        self.amount_ki_per_transformation = QtWidgets.QFrame(self.frame_2)
        self.amount_ki_per_transformation.setGeometry(QtCore.QRect(190, 100, 261, 81))
        self.amount_ki_per_transformation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.amount_ki_per_transformation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.amount_ki_per_transformation.setObjectName("amount_ki_per_transformation")
        self.amount_ki_per_transformation_text = QtWidgets.QLabel(self.amount_ki_per_transformation)
        self.amount_ki_per_transformation_text.setGeometry(QtCore.QRect(0, 10, 181, 16))
        self.amount_ki_per_transformation_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.amount_ki_per_transformation_text.setObjectName("amount_ki_per_transformation_text")
        self.amountKi_trans1_text = QtWidgets.QLabel(self.amount_ki_per_transformation)
        self.amountKi_trans1_text.setGeometry(QtCore.QRect(0, 30, 41, 20))
        self.amountKi_trans1_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_trans1_text.setScaledContents(False)
        self.amountKi_trans1_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_trans1_text.setObjectName("amountKi_trans1_text")
        self.amountKi_trans1_value = QtWidgets.QSpinBox(self.amount_ki_per_transformation)
        self.amountKi_trans1_value.setGeometry(QtCore.QRect(0, 50, 42, 22))
        self.amountKi_trans1_value.setMaximum(255)
        self.amountKi_trans1_value.setProperty("value", 0)
        self.amountKi_trans1_value.setObjectName("amountKi_trans1_value")
        self.amountKi_trans2_value = QtWidgets.QSpinBox(self.amount_ki_per_transformation)
        self.amountKi_trans2_value.setGeometry(QtCore.QRect(60, 50, 42, 22))
        self.amountKi_trans2_value.setMaximum(255)
        self.amountKi_trans2_value.setObjectName("amountKi_trans2_value")
        self.amountKi_trans2_text = QtWidgets.QLabel(self.amount_ki_per_transformation)
        self.amountKi_trans2_text.setGeometry(QtCore.QRect(60, 30, 41, 20))
        self.amountKi_trans2_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_trans2_text.setScaledContents(False)
        self.amountKi_trans2_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_trans2_text.setObjectName("amountKi_trans2_text")
        self.amountKi_trans3_value = QtWidgets.QSpinBox(self.amount_ki_per_transformation)
        self.amountKi_trans3_value.setGeometry(QtCore.QRect(120, 50, 42, 22))
        self.amountKi_trans3_value.setMaximum(255)
        self.amountKi_trans3_value.setObjectName("amountKi_trans3_value")
        self.amountKi_trans3_text = QtWidgets.QLabel(self.amount_ki_per_transformation)
        self.amountKi_trans3_text.setGeometry(QtCore.QRect(120, 30, 41, 20))
        self.amountKi_trans3_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_trans3_text.setScaledContents(False)
        self.amountKi_trans3_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_trans3_text.setObjectName("amountKi_trans3_text")
        self.amountKi_trans4_value = QtWidgets.QSpinBox(self.amount_ki_per_transformation)
        self.amountKi_trans4_value.setGeometry(QtCore.QRect(180, 50, 42, 22))
        self.amountKi_trans4_value.setMaximum(255)
        self.amountKi_trans4_value.setObjectName("amountKi_trans4_value")
        self.amountKi_trans4_text = QtWidgets.QLabel(self.amount_ki_per_transformation)
        self.amountKi_trans4_text.setGeometry(QtCore.QRect(180, 30, 41, 20))
        self.amountKi_trans4_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_trans4_text.setScaledContents(False)
        self.amountKi_trans4_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_trans4_text.setObjectName("amountKi_trans4_text")
        self.animation_per_transformation = QtWidgets.QFrame(self.frame_2)
        self.animation_per_transformation.setGeometry(QtCore.QRect(190, 180, 261, 111))
        self.animation_per_transformation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animation_per_transformation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animation_per_transformation.setObjectName("animation_per_transformation")
        self.animation_per_transformation_text = QtWidgets.QLabel(self.animation_per_transformation)
        self.animation_per_transformation_text.setGeometry(QtCore.QRect(0, 10, 181, 16))
        self.animation_per_transformation_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_per_transformation_text.setObjectName("animation_per_transformation_text")
        self.animation_trans1_text = QtWidgets.QLabel(self.animation_per_transformation)
        self.animation_trans1_text.setGeometry(QtCore.QRect(0, 40, 16, 20))
        self.animation_trans1_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_trans1_text.setScaledContents(False)
        self.animation_trans1_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_trans1_text.setObjectName("animation_trans1_text")
        self.animation_trans2_text = QtWidgets.QLabel(self.animation_per_transformation)
        self.animation_trans2_text.setGeometry(QtCore.QRect(0, 80, 16, 20))
        self.animation_trans2_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_trans2_text.setScaledContents(False)
        self.animation_trans2_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_trans2_text.setObjectName("animation_trans2_text")
        self.animation_trans3_text = QtWidgets.QLabel(self.animation_per_transformation)
        self.animation_trans3_text.setGeometry(QtCore.QRect(130, 40, 16, 20))
        self.animation_trans3_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_trans3_text.setScaledContents(False)
        self.animation_trans3_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_trans3_text.setObjectName("animation_trans3_text")
        self.animation_trans4_text = QtWidgets.QLabel(self.animation_per_transformation)
        self.animation_trans4_text.setGeometry(QtCore.QRect(130, 80, 16, 20))
        self.animation_trans4_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_trans4_text.setScaledContents(False)
        self.animation_trans4_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_trans4_text.setObjectName("animation_trans4_text")
        self.trans1_animation_value = QtWidgets.QComboBox(self.animation_per_transformation)
        self.trans1_animation_value.setGeometry(QtCore.QRect(20, 40, 91, 22))
        self.trans1_animation_value.setObjectName("trans1_animation_value")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans1_animation_value.addItem("")
        self.trans3_animation_value = QtWidgets.QComboBox(self.animation_per_transformation)
        self.trans3_animation_value.setGeometry(QtCore.QRect(150, 40, 91, 22))
        self.trans3_animation_value.setObjectName("trans3_animation_value")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans3_animation_value.addItem("")
        self.trans2_animation_value = QtWidgets.QComboBox(self.animation_per_transformation)
        self.trans2_animation_value.setGeometry(QtCore.QRect(20, 80, 91, 22))
        self.trans2_animation_value.setObjectName("trans2_animation_value")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans2_animation_value.addItem("")
        self.trans4_animation_value = QtWidgets.QComboBox(self.animation_per_transformation)
        self.trans4_animation_value.setGeometry(QtCore.QRect(150, 80, 91, 22))
        self.trans4_animation_value.setObjectName("trans4_animation_value")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.trans4_animation_value.addItem("")
        self.partnerPotara = QtWidgets.QFrame(self.frame_2)
        self.partnerPotara.setGeometry(QtCore.QRect(680, 0, 181, 51))
        self.partnerPotara.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.partnerPotara.setFrameShadow(QtWidgets.QFrame.Raised)
        self.partnerPotara.setObjectName("partnerPotara")
        self.partnerPotara_text = QtWidgets.QLabel(self.partnerPotara)
        self.partnerPotara_text.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.partnerPotara_text.setObjectName("partnerPotara_text")
        self.partnerPotara_value = QtWidgets.QLabel(self.partnerPotara)
        self.partnerPotara_value.setGeometry(QtCore.QRect(140, 10, 41, 41))
        self.partnerPotara_value.setText("")
        self.partnerPotara_value.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.partnerPotara_value.setScaledContents(True)
        self.partnerPotara_value.setObjectName("partnerPotara_value")
        self.partnerPotara_slot = QtWidgets.QLabel(self.partnerPotara)
        self.partnerPotara_slot.setGeometry(QtCore.QRect(140, 10, 41, 41))
        self.partnerPotara_slot.setText("")
        self.partnerPotara_slot.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/pl_slot.png"))
        self.partnerPotara_slot.setScaledContents(True)
        self.partnerPotara_slot.setObjectName("partnerPotara_slot")
        self.partnerPotara_slot.raise_()
        self.partnerPotara_text.raise_()
        self.partnerPotara_value.raise_()
        self.partnerMetamoran = QtWidgets.QFrame(self.frame_2)
        self.partnerMetamoran.setGeometry(QtCore.QRect(680, 60, 181, 41))
        self.partnerMetamoran.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.partnerMetamoran.setFrameShadow(QtWidgets.QFrame.Raised)
        self.partnerMetamoran.setObjectName("partnerMetamoran")
        self.partnerMetamoran_text = QtWidgets.QLabel(self.partnerMetamoran)
        self.partnerMetamoran_text.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.partnerMetamoran_text.setObjectName("partnerMetamoran_text")
        self.partnerMetamoran_value = QtWidgets.QLabel(self.partnerMetamoran)
        self.partnerMetamoran_value.setGeometry(QtCore.QRect(140, 0, 41, 41))
        self.partnerMetamoran_value.setText("")
        self.partnerMetamoran_value.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.partnerMetamoran_value.setScaledContents(True)
        self.partnerMetamoran_value.setObjectName("partnerMetamoran_value")
        self.partnerMetamoran_slot = QtWidgets.QLabel(self.partnerMetamoran)
        self.partnerMetamoran_slot.setGeometry(QtCore.QRect(140, 0, 41, 41))
        self.partnerMetamoran_slot.setText("")
        self.partnerMetamoran_slot.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/pl_slot.png"))
        self.partnerMetamoran_slot.setScaledContents(True)
        self.partnerMetamoran_slot.setObjectName("partnerMetamoran_slot")
        self.partnerMetamoran_slot.raise_()
        self.partnerMetamoran_text.raise_()
        self.partnerMetamoran_value.raise_()
        self.fusionPanel = QtWidgets.QFrame(self.frame_2)
        self.fusionPanel.setGeometry(QtCore.QRect(450, 40, 171, 181))
        self.fusionPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fusionPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fusionPanel.setObjectName("fusionPanel")
        self.fusiSlotPanel0 = QtWidgets.QLabel(self.fusionPanel)
        self.fusiSlotPanel0.setEnabled(True)
        self.fusiSlotPanel0.setGeometry(QtCore.QRect(33, 75, 61, 61))
        self.fusiSlotPanel0.setText("")
        self.fusiSlotPanel0.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.fusiSlotPanel0.setScaledContents(False)
        self.fusiSlotPanel0.setObjectName("fusiSlotPanel0")
        self.fusiSlotPanel1 = QtWidgets.QLabel(self.fusionPanel)
        self.fusiSlotPanel1.setGeometry(QtCore.QRect(65, 43, 61, 61))
        self.fusiSlotPanel1.setText("")
        self.fusiSlotPanel1.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.fusiSlotPanel1.setScaledContents(False)
        self.fusiSlotPanel1.setObjectName("fusiSlotPanel1")
        self.fusiSlotPanel2 = QtWidgets.QLabel(self.fusionPanel)
        self.fusiSlotPanel2.setGeometry(QtCore.QRect(99, 75, 61, 61))
        self.fusiSlotPanel2.setText("")
        self.fusiSlotPanel2.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.fusiSlotPanel2.setScaledContents(False)
        self.fusiSlotPanel2.setObjectName("fusiSlotPanel2")
        self.fusiSlotPanel3 = QtWidgets.QLabel(self.fusionPanel)
        self.fusiSlotPanel3.setGeometry(QtCore.QRect(65, 108, 61, 61))
        self.fusiSlotPanel3.setText("")
        self.fusiSlotPanel3.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/small/sc_chara_s_000.png"))
        self.fusiSlotPanel3.setScaledContents(False)
        self.fusiSlotPanel3.setObjectName("fusiSlotPanel3")
        self.fusiPanelText = QtWidgets.QLabel(self.fusionPanel)
        self.fusiPanelText.setGeometry(QtCore.QRect(56, 10, 81, 21))
        self.fusiPanelText.setText("")
        self.fusiPanelText.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/tx_fusion_US.png"))
        self.fusiPanelText.setScaledContents(True)
        self.fusiPanelText.setObjectName("fusiPanelText")
        self.fusiPanel = QtWidgets.QLabel(self.fusionPanel)
        self.fusiPanel.setGeometry(QtCore.QRect(30, 35, 141, 141))
        self.fusiPanel.setText("")
        self.fusiPanel.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/fourSlot/pl_fusion.png"))
        self.fusiPanel.setScaledContents(False)
        self.fusiPanel.setObjectName("fusiPanel")
        self.fusiPanel.raise_()
        self.fusiSlotPanel0.raise_()
        self.fusiSlotPanel1.raise_()
        self.fusiSlotPanel2.raise_()
        self.fusiSlotPanel3.raise_()
        self.fusiPanelText.raise_()
        self.amount_ki_per_fusion = QtWidgets.QFrame(self.frame_2)
        self.amount_ki_per_fusion.setGeometry(QtCore.QRect(620, 100, 251, 81))
        self.amount_ki_per_fusion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.amount_ki_per_fusion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.amount_ki_per_fusion.setObjectName("amount_ki_per_fusion")
        self.amount_ki_per_fusion_text = QtWidgets.QLabel(self.amount_ki_per_fusion)
        self.amount_ki_per_fusion_text.setGeometry(QtCore.QRect(70, 10, 131, 16))
        self.amount_ki_per_fusion_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.amount_ki_per_fusion_text.setObjectName("amount_ki_per_fusion_text")
        self.amountKi_fusion1_text = QtWidgets.QLabel(self.amount_ki_per_fusion)
        self.amountKi_fusion1_text.setGeometry(QtCore.QRect(20, 30, 41, 20))
        self.amountKi_fusion1_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_fusion1_text.setScaledContents(False)
        self.amountKi_fusion1_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_fusion1_text.setObjectName("amountKi_fusion1_text")
        self.amountKi_fusion1_value = QtWidgets.QSpinBox(self.amount_ki_per_fusion)
        self.amountKi_fusion1_value.setGeometry(QtCore.QRect(20, 50, 42, 22))
        self.amountKi_fusion1_value.setMaximum(255)
        self.amountKi_fusion1_value.setObjectName("amountKi_fusion1_value")
        self.amountKi_fusion2_value = QtWidgets.QSpinBox(self.amount_ki_per_fusion)
        self.amountKi_fusion2_value.setGeometry(QtCore.QRect(80, 50, 42, 22))
        self.amountKi_fusion2_value.setMaximum(255)
        self.amountKi_fusion2_value.setObjectName("amountKi_fusion2_value")
        self.amountKi_fusion2_text = QtWidgets.QLabel(self.amount_ki_per_fusion)
        self.amountKi_fusion2_text.setGeometry(QtCore.QRect(80, 30, 41, 20))
        self.amountKi_fusion2_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_fusion2_text.setScaledContents(False)
        self.amountKi_fusion2_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_fusion2_text.setObjectName("amountKi_fusion2_text")
        self.amountKi_fusion3_value = QtWidgets.QSpinBox(self.amount_ki_per_fusion)
        self.amountKi_fusion3_value.setGeometry(QtCore.QRect(140, 50, 42, 22))
        self.amountKi_fusion3_value.setMaximum(255)
        self.amountKi_fusion3_value.setObjectName("amountKi_fusion3_value")
        self.amountKi_fusion3_text = QtWidgets.QLabel(self.amount_ki_per_fusion)
        self.amountKi_fusion3_text.setGeometry(QtCore.QRect(140, 30, 41, 20))
        self.amountKi_fusion3_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_fusion3_text.setScaledContents(False)
        self.amountKi_fusion3_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_fusion3_text.setObjectName("amountKi_fusion3_text")
        self.amountKi_fusion4_value = QtWidgets.QSpinBox(self.amount_ki_per_fusion)
        self.amountKi_fusion4_value.setGeometry(QtCore.QRect(200, 50, 42, 22))
        self.amountKi_fusion4_value.setMaximum(255)
        self.amountKi_fusion4_value.setObjectName("amountKi_fusion4_value")
        self.amountKi_fusion4_text = QtWidgets.QLabel(self.amount_ki_per_fusion)
        self.amountKi_fusion4_text.setGeometry(QtCore.QRect(200, 30, 41, 20))
        self.amountKi_fusion4_text.setTextFormat(QtCore.Qt.PlainText)
        self.amountKi_fusion4_text.setScaledContents(False)
        self.amountKi_fusion4_text.setAlignment(QtCore.Qt.AlignCenter)
        self.amountKi_fusion4_text.setObjectName("amountKi_fusion4_text")
        self.animation_per_fusion = QtWidgets.QFrame(self.frame_2)
        self.animation_per_fusion.setGeometry(QtCore.QRect(620, 180, 251, 111))
        self.animation_per_fusion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animation_per_fusion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animation_per_fusion.setObjectName("animation_per_fusion")
        self.animation_per_fusion_text = QtWidgets.QLabel(self.animation_per_fusion)
        self.animation_per_fusion_text.setGeometry(QtCore.QRect(80, 10, 131, 16))
        self.animation_per_fusion_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_per_fusion_text.setObjectName("animation_per_fusion_text")
        self.animation_fusion1_text = QtWidgets.QLabel(self.animation_per_fusion)
        self.animation_fusion1_text.setGeometry(QtCore.QRect(0, 40, 16, 20))
        self.animation_fusion1_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_fusion1_text.setScaledContents(False)
        self.animation_fusion1_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_fusion1_text.setObjectName("animation_fusion1_text")
        self.animation_fusion2_text = QtWidgets.QLabel(self.animation_per_fusion)
        self.animation_fusion2_text.setGeometry(QtCore.QRect(0, 80, 16, 20))
        self.animation_fusion2_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_fusion2_text.setScaledContents(False)
        self.animation_fusion2_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_fusion2_text.setObjectName("animation_fusion2_text")
        self.animation_fusion3_text = QtWidgets.QLabel(self.animation_per_fusion)
        self.animation_fusion3_text.setGeometry(QtCore.QRect(130, 40, 16, 20))
        self.animation_fusion3_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_fusion3_text.setScaledContents(False)
        self.animation_fusion3_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_fusion3_text.setObjectName("animation_fusion3_text")
        self.animation_fusion4_text = QtWidgets.QLabel(self.animation_per_fusion)
        self.animation_fusion4_text.setGeometry(QtCore.QRect(130, 80, 16, 20))
        self.animation_fusion4_text.setTextFormat(QtCore.Qt.PlainText)
        self.animation_fusion4_text.setScaledContents(False)
        self.animation_fusion4_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.animation_fusion4_text.setObjectName("animation_fusion4_text")
        self.fusion1_animation_value = QtWidgets.QComboBox(self.animation_per_fusion)
        self.fusion1_animation_value.setGeometry(QtCore.QRect(20, 40, 91, 22))
        self.fusion1_animation_value.setObjectName("fusion1_animation_value")
        self.fusion1_animation_value.addItem("")
        self.fusion1_animation_value.addItem("")
        self.fusion3_animation_value = QtWidgets.QComboBox(self.animation_per_fusion)
        self.fusion3_animation_value.setGeometry(QtCore.QRect(150, 40, 91, 22))
        self.fusion3_animation_value.setObjectName("fusion3_animation_value")
        self.fusion3_animation_value.addItem("")
        self.fusion3_animation_value.addItem("")
        self.fusion2_animation_value = QtWidgets.QComboBox(self.animation_per_fusion)
        self.fusion2_animation_value.setGeometry(QtCore.QRect(20, 80, 91, 22))
        self.fusion2_animation_value.setObjectName("fusion2_animation_value")
        self.fusion2_animation_value.addItem("")
        self.fusion2_animation_value.addItem("")
        self.fusion4_animation_value = QtWidgets.QComboBox(self.animation_per_fusion)
        self.fusion4_animation_value.setGeometry(QtCore.QRect(150, 80, 91, 22))
        self.fusion4_animation_value.setObjectName("fusion4_animation_value")
        self.fusion4_animation_value.addItem("")
        self.fusion4_animation_value.addItem("")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.tabWidget.addTab(self.character_parameters_editor, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenSPRVRAM = QtWidgets.QAction(MainWindow)
        self.actionOpenSPRVRAM.setObjectName("actionOpenSPRVRAM")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSaveSPRVRAM = QtWidgets.QAction(MainWindow)
        self.actionSaveSPRVRAM.setObjectName("actionSaveSPRVRAM")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.actionOpenPAK = QtWidgets.QAction(MainWindow)
        self.actionOpenPAK.setObjectName("actionOpenPAK")
        self.actionSavePAK = QtWidgets.QAction(MainWindow)
        self.actionSavePAK.setObjectName("actionSavePAK")
        self.menuFIle.addAction(self.actionOpenSPRVRAM)
        self.menuFIle.addAction(self.actionSaveSPRVRAM)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionOpenPAK)
        self.menuFIle.addAction(self.actionSavePAK)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionClose)
        self.menuFIle.addSeparator()
        self.menuAbout.addAction(self.actionAuthor)
        self.menuAbout.addAction(self.actionCredits)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raging tools 1.0"))
        self.exportButton.setText(_translate("MainWindow", "E&xport..."))
        self.importButton.setText(_translate("MainWindow", "I&mport..."))
        self.exportAllButton.setText(_translate("MainWindow", "Export all"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vram_explorer), _translate("MainWindow", "vram explorer"))
        self.transEffectValue.setItemText(0, _translate("MainWindow", "Super Saiyan"))
        self.transEffectValue.setItemText(1, _translate("MainWindow", "Metamoru"))
        self.transEffectValue.setItemText(2, _translate("MainWindow", "Potara"))
        self.transEffectValue.setItemText(3, _translate("MainWindow", "Cell"))
        self.transEffectValue.setItemText(4, _translate("MainWindow", "Super Buu"))
        self.transEffectValue.setItemText(5, _translate("MainWindow", "Broly"))
        self.transEffectValue.setItemText(6, _translate("MainWindow", "Freezer"))
        self.transEffectValue.setItemText(7, _translate("MainWindow", "Super Saiyan 3"))
        self.transEffectValue.setItemText(8, _translate("MainWindow", "Cooler"))
        self.transEffectValue.setItemText(9, _translate("MainWindow", "Bojack"))
        self.transEffectValue.setItemText(10, _translate("MainWindow", "C-13"))
        self.transEffectValue.setItemText(11, _translate("MainWindow", "Nothing"))
        self.transEffectText.setText(_translate("MainWindow", "Transformation effect/Ki:"))
        self.transPartnerText.setText(_translate("MainWindow", "Trasformation partner:"))
        self.amount_ki_per_transformation_text.setText(_translate("MainWindow", "Amount Ki per transformation:"))
        self.amountKi_trans1_text.setText(_translate("MainWindow", "1"))
        self.amountKi_trans2_text.setText(_translate("MainWindow", "2"))
        self.amountKi_trans3_text.setText(_translate("MainWindow", "3"))
        self.amountKi_trans4_text.setText(_translate("MainWindow", "4"))
        self.animation_per_transformation_text.setText(_translate("MainWindow", "Animation per transformation:"))
        self.animation_trans1_text.setText(_translate("MainWindow", "1"))
        self.animation_trans2_text.setText(_translate("MainWindow", "2"))
        self.animation_trans3_text.setText(_translate("MainWindow", "3"))
        self.animation_trans4_text.setText(_translate("MainWindow", "4"))
        self.trans1_animation_value.setItemText(0, _translate("MainWindow", "Transform"))
        self.trans1_animation_value.setItemText(1, _translate("MainWindow", "Return"))
        self.trans1_animation_value.setItemText(2, _translate("MainWindow", "UNK2"))
        self.trans1_animation_value.setItemText(3, _translate("MainWindow", "UNK3"))
        self.trans1_animation_value.setItemText(4, _translate("MainWindow", "Transform 2"))
        self.trans1_animation_value.setItemText(5, _translate("MainWindow", "UNK5"))
        self.trans1_animation_value.setItemText(6, _translate("MainWindow", "Absorb"))
        self.trans1_animation_value.setItemText(7, _translate("MainWindow", "UNK7"))
        self.trans1_animation_value.setItemText(8, _translate("MainWindow", "UNK8"))
        self.trans1_animation_value.setItemText(9, _translate("MainWindow", "UNK9"))
        self.trans1_animation_value.setItemText(10, _translate("MainWindow", "UNK10"))
        self.trans1_animation_value.setItemText(11, _translate("MainWindow", "UNK11"))
        self.trans1_animation_value.setItemText(12, _translate("MainWindow", "Special"))
        self.trans3_animation_value.setItemText(0, _translate("MainWindow", "Transform"))
        self.trans3_animation_value.setItemText(1, _translate("MainWindow", "Return"))
        self.trans3_animation_value.setItemText(2, _translate("MainWindow", "UNK2"))
        self.trans3_animation_value.setItemText(3, _translate("MainWindow", "UNK3"))
        self.trans3_animation_value.setItemText(4, _translate("MainWindow", "Transform 2"))
        self.trans3_animation_value.setItemText(5, _translate("MainWindow", "UNK5"))
        self.trans3_animation_value.setItemText(6, _translate("MainWindow", "Absorb"))
        self.trans3_animation_value.setItemText(7, _translate("MainWindow", "UNK7"))
        self.trans3_animation_value.setItemText(8, _translate("MainWindow", "UNK8"))
        self.trans3_animation_value.setItemText(9, _translate("MainWindow", "UNK9"))
        self.trans3_animation_value.setItemText(10, _translate("MainWindow", "UNK10"))
        self.trans3_animation_value.setItemText(11, _translate("MainWindow", "UNK11"))
        self.trans3_animation_value.setItemText(12, _translate("MainWindow", "Special"))
        self.trans2_animation_value.setItemText(0, _translate("MainWindow", "Transform"))
        self.trans2_animation_value.setItemText(1, _translate("MainWindow", "Return"))
        self.trans2_animation_value.setItemText(2, _translate("MainWindow", "UNK2"))
        self.trans2_animation_value.setItemText(3, _translate("MainWindow", "UNK3"))
        self.trans2_animation_value.setItemText(4, _translate("MainWindow", "Transform 2"))
        self.trans2_animation_value.setItemText(5, _translate("MainWindow", "UNK5"))
        self.trans2_animation_value.setItemText(6, _translate("MainWindow", "Absorb"))
        self.trans2_animation_value.setItemText(7, _translate("MainWindow", "UNK7"))
        self.trans2_animation_value.setItemText(8, _translate("MainWindow", "UNK8"))
        self.trans2_animation_value.setItemText(9, _translate("MainWindow", "UNK9"))
        self.trans2_animation_value.setItemText(10, _translate("MainWindow", "UNK10"))
        self.trans2_animation_value.setItemText(11, _translate("MainWindow", "UNK11"))
        self.trans2_animation_value.setItemText(12, _translate("MainWindow", "Special"))
        self.trans4_animation_value.setItemText(0, _translate("MainWindow", "Transform"))
        self.trans4_animation_value.setItemText(1, _translate("MainWindow", "Return"))
        self.trans4_animation_value.setItemText(2, _translate("MainWindow", "UNK2"))
        self.trans4_animation_value.setItemText(3, _translate("MainWindow", "UNK3"))
        self.trans4_animation_value.setItemText(4, _translate("MainWindow", "Transform 2"))
        self.trans4_animation_value.setItemText(5, _translate("MainWindow", "UNK5"))
        self.trans4_animation_value.setItemText(6, _translate("MainWindow", "Absorb"))
        self.trans4_animation_value.setItemText(7, _translate("MainWindow", "UNK7"))
        self.trans4_animation_value.setItemText(8, _translate("MainWindow", "UNK8"))
        self.trans4_animation_value.setItemText(9, _translate("MainWindow", "UNK9"))
        self.trans4_animation_value.setItemText(10, _translate("MainWindow", "UNK10"))
        self.trans4_animation_value.setItemText(11, _translate("MainWindow", "UNK11"))
        self.trans4_animation_value.setItemText(12, _translate("MainWindow", "Special"))
        self.partnerPotara_text.setText(_translate("MainWindow", "Partner potara:"))
        self.partnerMetamoran_text.setText(_translate("MainWindow", "Partner metamoran:"))
        self.amount_ki_per_fusion_text.setText(_translate("MainWindow", "Amount Ki per fusion:"))
        self.amountKi_fusion1_text.setText(_translate("MainWindow", "1"))
        self.amountKi_fusion2_text.setText(_translate("MainWindow", "2"))
        self.amountKi_fusion3_text.setText(_translate("MainWindow", "3"))
        self.amountKi_fusion4_text.setText(_translate("MainWindow", "4"))
        self.animation_per_fusion_text.setText(_translate("MainWindow", "Animation per fusion:"))
        self.animation_fusion1_text.setText(_translate("MainWindow", "1"))
        self.animation_fusion2_text.setText(_translate("MainWindow", "2"))
        self.animation_fusion3_text.setText(_translate("MainWindow", "3"))
        self.animation_fusion4_text.setText(_translate("MainWindow", "4"))
        self.fusion1_animation_value.setItemText(0, _translate("MainWindow", "Nothing"))
        self.fusion1_animation_value.setItemText(1, _translate("MainWindow", "Potara"))
        self.fusion3_animation_value.setItemText(0, _translate("MainWindow", "Nothing"))
        self.fusion3_animation_value.setItemText(1, _translate("MainWindow", "Potara"))
        self.fusion2_animation_value.setItemText(0, _translate("MainWindow", "Nothing"))
        self.fusion2_animation_value.setItemText(1, _translate("MainWindow", "Potara"))
        self.fusion4_animation_value.setItemText(0, _translate("MainWindow", "Nothing"))
        self.fusion4_animation_value.setItemText(1, _translate("MainWindow", "Potara"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.character_parameters_editor), _translate("MainWindow", "character parameters editor"))
        self.menuFIle.setTitle(_translate("MainWindow", "&File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpenSPRVRAM.setText(_translate("MainWindow", "Open spr/vram..."))
        self.actionClose.setText(_translate("MainWindow", "E&xit"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSaveSPRVRAM.setText(_translate("MainWindow", "Save spr/vram"))
        self.actionAuthor.setText(_translate("MainWindow", "A&uthor"))
        self.actionAuthor.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionCredits.setText(_translate("MainWindow", "C&redits"))
        self.actionCredits.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionOpenPAK.setText(_translate("MainWindow", "Open pak..."))
        self.actionSavePAK.setText(_translate("MainWindow", "Save pak..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

