# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_chara.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Select_Chara(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 770)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setEnabled(True)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_0 = QtWidgets.QLabel(self.frame)
        self.label_0.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.label_0.setText("")
        self.label_0.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_0.setScaledContents(True)
        self.label_0.setObjectName("label_0")
        self.label_1 = QtWidgets.QLabel(self.frame)
        self.label_1.setGeometry(QtCore.QRect(70, 0, 71, 71))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 0, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(210, 0, 71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(280, 0, 71, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(350, 0, 71, 71))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(420, 0, 71, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(490, 0, 71, 71))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(560, 0, 71, 71))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(630, 0, 71, 71))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(0, 70, 71, 71))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(70, 70, 71, 71))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(140, 70, 71, 71))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(210, 70, 71, 71))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(280, 70, 71, 71))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(350, 70, 71, 71))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(420, 70, 71, 71))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(490, 70, 71, 71))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(560, 70, 71, 71))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(630, 70, 71, 71))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(0, 140, 71, 71))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(70, 140, 71, 71))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(140, 140, 71, 71))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(210, 140, 71, 71))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(280, 140, 71, 71))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(350, 140, 71, 71))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(420, 140, 71, 71))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(490, 140, 71, 71))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(560, 140, 71, 71))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(630, 140, 71, 71))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(0, 210, 71, 71))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(70, 210, 71, 71))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(140, 210, 71, 71))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(210, 210, 71, 71))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(280, 210, 71, 71))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(350, 210, 71, 71))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(420, 210, 71, 71))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(490, 210, 71, 71))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame)
        self.label_38.setGeometry(QtCore.QRect(560, 210, 71, 71))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.frame)
        self.label_39.setGeometry(QtCore.QRect(630, 210, 71, 71))
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame)
        self.label_40.setGeometry(QtCore.QRect(0, 280, 71, 71))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame)
        self.label_41.setGeometry(QtCore.QRect(70, 280, 71, 71))
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame)
        self.label_42.setGeometry(QtCore.QRect(140, 280, 71, 71))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame)
        self.label_43.setGeometry(QtCore.QRect(210, 280, 71, 71))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame)
        self.label_44.setGeometry(QtCore.QRect(280, 280, 71, 71))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame)
        self.label_45.setGeometry(QtCore.QRect(350, 280, 71, 71))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame)
        self.label_46.setGeometry(QtCore.QRect(420, 280, 71, 71))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame)
        self.label_47.setGeometry(QtCore.QRect(490, 280, 71, 71))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame)
        self.label_48.setGeometry(QtCore.QRect(560, 280, 71, 71))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame)
        self.label_49.setGeometry(QtCore.QRect(630, 280, 71, 71))
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame)
        self.label_50.setGeometry(QtCore.QRect(0, 350, 71, 71))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame)
        self.label_51.setGeometry(QtCore.QRect(70, 350, 71, 71))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.frame)
        self.label_52.setGeometry(QtCore.QRect(140, 350, 71, 71))
        self.label_52.setText("")
        self.label_52.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_52.setScaledContents(True)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.frame)
        self.label_53.setGeometry(QtCore.QRect(210, 350, 71, 71))
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.frame)
        self.label_54.setGeometry(QtCore.QRect(280, 350, 71, 71))
        self.label_54.setText("")
        self.label_54.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame)
        self.label_55.setGeometry(QtCore.QRect(350, 350, 71, 71))
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame)
        self.label_56.setGeometry(QtCore.QRect(420, 350, 71, 71))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.frame)
        self.label_57.setGeometry(QtCore.QRect(490, 350, 71, 71))
        self.label_57.setText("")
        self.label_57.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame)
        self.label_58.setGeometry(QtCore.QRect(560, 350, 71, 71))
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.frame)
        self.label_59.setGeometry(QtCore.QRect(630, 350, 71, 71))
        self.label_59.setText("")
        self.label_59.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_59.setScaledContents(True)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.frame)
        self.label_60.setGeometry(QtCore.QRect(0, 420, 71, 71))
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.frame)
        self.label_61.setGeometry(QtCore.QRect(70, 420, 71, 71))
        self.label_61.setText("")
        self.label_61.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_61.setScaledContents(True)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.frame)
        self.label_62.setGeometry(QtCore.QRect(140, 420, 71, 71))
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.frame)
        self.label_63.setGeometry(QtCore.QRect(210, 420, 71, 71))
        self.label_63.setText("")
        self.label_63.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_63.setScaledContents(True)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.frame)
        self.label_64.setGeometry(QtCore.QRect(280, 420, 71, 71))
        self.label_64.setText("")
        self.label_64.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_64.setScaledContents(True)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.frame)
        self.label_65.setGeometry(QtCore.QRect(350, 420, 71, 71))
        self.label_65.setText("")
        self.label_65.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_65.setScaledContents(True)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.frame)
        self.label_66.setGeometry(QtCore.QRect(420, 420, 71, 71))
        self.label_66.setText("")
        self.label_66.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.frame)
        self.label_67.setGeometry(QtCore.QRect(490, 420, 71, 71))
        self.label_67.setText("")
        self.label_67.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_67.setScaledContents(True)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.frame)
        self.label_68.setGeometry(QtCore.QRect(560, 420, 71, 71))
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_68.setScaledContents(True)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.frame)
        self.label_69.setGeometry(QtCore.QRect(630, 420, 71, 71))
        self.label_69.setText("")
        self.label_69.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_69.setScaledContents(True)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.frame)
        self.label_70.setGeometry(QtCore.QRect(0, 490, 71, 71))
        self.label_70.setText("")
        self.label_70.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_70.setScaledContents(True)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.frame)
        self.label_71.setGeometry(QtCore.QRect(70, 490, 71, 71))
        self.label_71.setText("")
        self.label_71.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_71.setScaledContents(True)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.frame)
        self.label_72.setGeometry(QtCore.QRect(140, 490, 71, 71))
        self.label_72.setText("")
        self.label_72.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_72.setScaledContents(True)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.frame)
        self.label_73.setGeometry(QtCore.QRect(210, 490, 71, 71))
        self.label_73.setText("")
        self.label_73.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_73.setScaledContents(True)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.frame)
        self.label_74.setGeometry(QtCore.QRect(280, 490, 71, 71))
        self.label_74.setText("")
        self.label_74.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_74.setScaledContents(True)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.frame)
        self.label_75.setGeometry(QtCore.QRect(350, 490, 71, 71))
        self.label_75.setText("")
        self.label_75.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_75.setScaledContents(True)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.frame)
        self.label_76.setGeometry(QtCore.QRect(420, 490, 71, 71))
        self.label_76.setText("")
        self.label_76.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_76.setScaledContents(True)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.frame)
        self.label_77.setGeometry(QtCore.QRect(490, 490, 71, 71))
        self.label_77.setText("")
        self.label_77.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_77.setScaledContents(True)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.frame)
        self.label_78.setGeometry(QtCore.QRect(560, 490, 71, 71))
        self.label_78.setText("")
        self.label_78.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_78.setScaledContents(True)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.frame)
        self.label_79.setGeometry(QtCore.QRect(630, 490, 71, 71))
        self.label_79.setText("")
        self.label_79.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_79.setScaledContents(True)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.frame)
        self.label_80.setGeometry(QtCore.QRect(0, 560, 71, 71))
        self.label_80.setText("")
        self.label_80.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_80.setScaledContents(True)
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.frame)
        self.label_81.setGeometry(QtCore.QRect(70, 560, 71, 71))
        self.label_81.setText("")
        self.label_81.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_81.setScaledContents(True)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.frame)
        self.label_82.setGeometry(QtCore.QRect(140, 560, 71, 71))
        self.label_82.setText("")
        self.label_82.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_82.setScaledContents(True)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.frame)
        self.label_83.setGeometry(QtCore.QRect(210, 560, 71, 71))
        self.label_83.setText("")
        self.label_83.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_83.setScaledContents(True)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.frame)
        self.label_84.setGeometry(QtCore.QRect(280, 560, 71, 71))
        self.label_84.setText("")
        self.label_84.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_84.setScaledContents(True)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.frame)
        self.label_85.setGeometry(QtCore.QRect(350, 560, 71, 71))
        self.label_85.setText("")
        self.label_85.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_85.setScaledContents(True)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.frame)
        self.label_86.setGeometry(QtCore.QRect(420, 560, 71, 71))
        self.label_86.setText("")
        self.label_86.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_86.setScaledContents(True)
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.frame)
        self.label_87.setGeometry(QtCore.QRect(490, 560, 71, 71))
        self.label_87.setText("")
        self.label_87.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_87.setScaledContents(True)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.frame)
        self.label_88.setGeometry(QtCore.QRect(560, 560, 71, 71))
        self.label_88.setText("")
        self.label_88.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_88.setScaledContents(True)
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.frame)
        self.label_89.setGeometry(QtCore.QRect(630, 560, 71, 71))
        self.label_89.setText("")
        self.label_89.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_89.setScaledContents(True)
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.frame)
        self.label_90.setGeometry(QtCore.QRect(0, 630, 71, 71))
        self.label_90.setText("")
        self.label_90.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_90.setScaledContents(True)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.frame)
        self.label_91.setGeometry(QtCore.QRect(70, 630, 71, 71))
        self.label_91.setText("")
        self.label_91.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_91.setScaledContents(True)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.frame)
        self.label_92.setGeometry(QtCore.QRect(140, 630, 71, 71))
        self.label_92.setText("")
        self.label_92.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_92.setScaledContents(True)
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.frame)
        self.label_93.setGeometry(QtCore.QRect(210, 630, 71, 71))
        self.label_93.setText("")
        self.label_93.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_93.setScaledContents(True)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.frame)
        self.label_94.setGeometry(QtCore.QRect(280, 630, 71, 71))
        self.label_94.setText("")
        self.label_94.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.frame)
        self.label_95.setGeometry(QtCore.QRect(350, 630, 71, 71))
        self.label_95.setText("")
        self.label_95.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_95.setScaledContents(True)
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.frame)
        self.label_96.setGeometry(QtCore.QRect(420, 630, 71, 71))
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.frame)
        self.label_97.setGeometry(QtCore.QRect(490, 630, 71, 71))
        self.label_97.setText("")
        self.label_97.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_97.setScaledContents(True)
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.frame)
        self.label_98.setGeometry(QtCore.QRect(560, 630, 71, 71))
        self.label_98.setText("")
        self.label_98.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_98.setScaledContents(True)
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QLabel(self.frame)
        self.label_99.setGeometry(QtCore.QRect(630, 630, 71, 71))
        self.label_99.setText("")
        self.label_99.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_99.setScaledContents(True)
        self.label_99.setObjectName("label_99")
        self.label_101 = QtWidgets.QLabel(self.frame)
        self.label_101.setGeometry(QtCore.QRect(0, 700, 71, 71))
        self.label_101.setText("")
        self.label_101.setPixmap(QtGui.QPixmap("../character_parameters_editor/images/small/chara_chips_000.bmp"))
        self.label_101.setScaledContents(True)
        self.label_101.setObjectName("label_101")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select character"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Select_Chara()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

